# ============================================================
# DATASOURCE - PostgreSQL
# ============================================================
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5433}/${DB_NAME:prode_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# JPA / HIBERNATE
# ============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ============================================================
# JWT
# ============================================================
jwt.secret=${JWT_SECRET:1de9283bf713642214643c54a5487446f6cf29dcf30e8094b4fa9136c8984013}
jwt.expiration=86400000

# ============================================================
# SCHEDULER - API Football
# ============================================================
football.api.base-url=https://api.football-data.org/v4
football.api.token=${FOOTBALL_API_TOKEN:3ace133c10154d9dbc18b2c89cdda85a}

# ============================================================
# CORS
# ============================================================
app.cors.allowed-origins=${CORS_ORIGINS:*}

# ============================================================
# GENERAL
# ============================================================
server.port=8080
spring.application.name=prode
logging.level.com.utn.prode.scheduler=INFO