# ============================================================
# DATASOURCE - PostgreSQL
# ============================================================
spring.datasource.url=jdbc:postgresql://localhost:5432/prode_db
spring.datasource.username=postgres
spring.datasource.password=postgres
spring.datasource.driver-class-name=org.postgresql.Driver

# ============================================================
# JPA / HIBERNATE
# ============================================================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
# Toda fecha se persiste en UTC
spring.jpa.properties.hibernate.jdbc.time_zone=UTC

# ============================================================
# JWT
# ============================================================
# Cambiar por un valor secreto real en produccion (min 256 bits)
jwt.secret=1de9283bf713642214643c54a5487446f6cf29dcf30e8094b4fa9136c8984013
jwt.expiration=86400000

# ============================================================
# SCHEDULER - API Football
# ============================================================
football.api.base-url=https://api.football-data.org/v4
# Obtener en https://www.football-data.org/client/register
football.api.token=3ace133c10154d9dbc18b2c89cdda85a

# ============================================================
# GENERAL
# ============================================================
server.port=8080
spring.application.name=prode